DROP SEQUENCE BOARDNOSEQ;
DROP SEQUENCE GROUPNOSEQ;
DROP TABLE ANSWERBOARD;

CREATE SEQUENCE BOARDNOSEQ;
CREATE SEQUENCE GROUPNOSEQ;

CREATE TABLE ANSWERBOARD(
	BOARDNO NUMBER NOT NULL,
	GROUPNO NUMBER NOT NULL,
	GROUPSEQ NUMBER NOT NULL,
	TITLETAB NUMBER NOT NULL,
	DELFLAG VARCHAR2(2) NOT NULL,
	TITLE VARCHAR2(1000) NOT NULL,
	CONTENT VARCHAR2(4000) NOT NULL,
	WRITER VARCHAR2(500) NOT NULL,
	REGDATE DATE NOT NULL,
	
	CONSTRAINT ANSWER_BOARDNO_PK PRIMARY KEY (BOARDNO),
	CONSTRAINT ANSWER_DELFLAG_CK CHECK(DELFLAG IN ('Y', 'N'))
);

--1. 글작성
INSERT INTO ANSWERBOARD
VALUES(BOARDNOSEQ.NEXTVAL, GROUPNOSEQ.NEXTVAL, 1, 0, 'N', '답변형재밌다', '정말재밌다.', '반장', SYSDATE);

--1번글에 답글
--UPDATE
--부모의 그룹번호와 같은 그룹이면서
--부모의 그룹 순서보다 더 큰 글들에
--그룹순서 +1
UPDATE ANSWERBOARD
SET GROUPSEQ = GROUPSEQ +1
WHERE GROUPNO = (SELECT GROUPNO FROM ANSWERBOARD WHERE BOARDNO = 1)
AND GROUPSEQ > (SELECT GROUPSEQ FROM ANSWERBOARD WHERE BOARDNO = 1);

--INSERT
INSERT INTO ANSWERBOARD
VALUES(BOARDNOSEQ.NEXTVAL,
		(SELECT GROUPNO FROM ANSWERBOARD WHERE BOARDNO = 1),
		(SELECT GROUPSEQ FROM ANSWERBOARD WHERE BOARDNO =1)+1,
		(SELECT TITLETAB + 1 FROM ANSWERBOARD WHERE BOARDNO=1),
		'N', 'RE:답변형 재밌다.', '진짜 재미있는거 맞아?', '강사', SYSDATE);

--1번글 삭제
UPDATE ANSWERBOARD
SET DELFLAG = 'Y'
WHERE BOARDNO = 1;

SELECT BOARDNO, GROUPNO, GROUPSEQ, TITLETAB, DELFLAG, TITLE, CONTENT, WRITER, REGDATE
FROM ANSWERBOARD
ORDER BY GROUPNO DESC, GROUPSEQ;